#!/bin/bash

DEVICE='E4:92:82:E1:F2:3F'
STATUS=$(echo -e "info $DEVICE" | bluetoothctl | awk '/Connected:/{ print $2 }')

if [ $STATUS == 'no' ]; then
    bluetoothctl connect $DEVICE
else
    bluetoothctl disconnect $DEVICE
fi
