#!/bin/bash

dev=$(lsblk -dlnpo name,size | sed -e '/^\/dev\/sda/d' -e '/^\/dev\/sdb/d' | awk '{print $1 " ["$2"]"}' | dmenu -b -h 19 -i -fn 'DejaVu Sans Mono-9' -nb '#000000' -nf '#888888' -sb '#263238')

if [ -z "$dev" ]; then exit; fi
dev=$(echo "$dev" | awk '{print $1}')
echo Unpowering "$dev"...

parts=($(lsblk -lnp "$dev" -o name | tail -n +2))
for part in "${parts[@]}"
do
    udisksctl unmount -b "$part" > /dev/null && echo "    ""$part" unmounted
done

udisksctl power-off -b "$dev" && echo "$dev" unpowered
