#!/bin/bash

if [ -$1 == '--a' ]; then
    activ_win_id=$(xprop -root _NET_ACTIVE_WINDOW)
    if [ "${activ_win_id: -3}" != "0x0" ]; then
        xprop -id "${activ_win_id:40:9}" | grep _NET_WM_STATE_FULLSCREEN > /dev/null
    if [ $? -eq 0 ]; then
            exit
        fi
    fi
fi

pkill -u "$USER" -USR1 dunst
#xautolock -disable
pkill xautolock
xset dpms

if [ -$1 != '--s' ]; then
    xset dpms force off
fi

xinput --disable 'pointer:Logitech B330/M330/M3'
xinput --disable 'pointer:Razer Razer DeathAdder Chroma'
xinput --disable 'SynPS/2 Synaptics TouchPad'

i3lock -e -n -i "$HOME/Documents/wallpapers/login_bg.png" \
    --clock \
    --date-str='%A, %d-%b-%Y' \
    --time-color=ffffffff \
    --date-color=ffffffff \
    --line-color=00000000 \
    --line-color=00000000 \
    --insidever-color=00000000 \
    --insidewrong-color=00000000 \
    --inside-color=00000000 \
    --ringver-color=00000000 \
    --ringwrong-color=00000000 \
    --ring-color=00000000 \
    --verif-color=ffffffff \
    --wrong-color=ffffffff \
    --layout-color=ffffffff \
    --ring-color=00000000 \
    --separator-color=00000000 \
    --keyhl-color=00000000 \
    --bshl-color=00000000 \
    --composite

xset -dpms
#xautolock -enable
xautolock -time 10 -locker 'lock -a' -detectsleep &
pkill -u "$USER" -USR2 dunst

xinput --enable 'SynPS/2 Synaptics TouchPad'
xinput --enable 'pointer:Razer Razer DeathAdder Chroma'
xinput --enable 'pointer:Logitech B330/M330/M3'
