#!/bin/bash

if [ -$1 == '--a' ]; then
    activ_win_id=$(xprop -root _NET_ACTIVE_WINDOW)
    if [ "${activ_win_id: -3}" != "0x0" ]; then
        xprop -id "${activ_win_id:40:9}" | grep _NET_WM_STATE_FULLSCREEN > /dev/null
    if [ $? -eq 0 ]; then
            exit
        fi
    fi
fi

pkill -u "$USER" -USR1 dunst
#xautolock -disable
pkill xautolock
xset dpms

if [ -$1 != '--s' ]; then
    xset dpms force off
fi

xinput --disable 'pointer:Logitech B330/M330/M3'
xinput --disable 'pointer:Razer Razer DeathAdder Chroma'
xinput --disable 'SynPS/2 Synaptics TouchPad'

i3lock -e -n -i "$HOME/Documents/wallpapers/login_bg.png" \
    --clock \
    --datestr='%A, %d-%b-%Y' \
    --timecolor=ffffffff \
    --datecolor=ffffffff \
    --linecolor=00000000 \
    --linecolor=00000000 \
    --insidevercolor=00000000 \
    --insidewrongcolor=00000000 \
    --insidecolor=00000000 \
    --ringvercolor=00000000 \
    --ringwrongcolor=00000000 \
    --ringcolor=00000000 \
    --verifcolor=ffffffff \
    --wrongcolor=ffffffff \
    --layoutcolor=ffffffff \
    --ringcolor=00000000 \
    --separatorcolor=00000000 \
    --keyhlcolor=00000000 \
    --bshlcolor=00000000 \
    --composite

xset -dpms
#xautolock -enable
xautolock -time 10 -locker 'lock -a' -detectsleep &
pkill -u "$USER" -USR2 dunst

xinput --enable 'SynPS/2 Synaptics TouchPad'
xinput --enable 'pointer:Razer Razer DeathAdder Chroma'
xinput --enable 'pointer:Logitech B330/M330/M3'
