#!/bin/zsh

set -ue

local password_store="$HOME/.password-store"

if [[ ! -d "$password_store" ]]; then
    printf "Configure \$password_store within $(command -v dmenu-pass-autotype).\n" 1>&2
    printf "Its default location, $password_store, does not exist.\n" 1>&2
    exit 1
fi

local candidates="$(find "$password_store" -name '*gpg' -print0 |
tr "\0" "\n" |
sed "s#$password_store/##;s#\.gpg\$##")"

local choice="$(printf "$candidates" | sort | dmenu -b -h 19 -i -fn 'DejaVu Sans Mono-9' -nb '#000000' -nf '#888888' -sb '#263238')"
#local choice="$(printf "$candidates" | sort | rofi -dmenu -i -p "Password: ")"

if [[ -n "$choice" ]]; then
    printf "Using $choice.\n" 1>&2
    exec pass-autotype "$choice" $*
else
    printf "Nothing choosen.\n" 1>&2
fi
