#!/bin/bash

PIDS=$(xdotool search --class "Alacritty")

EXISTS=0
for PID in $PIDS; do
    TITLE=$(xdotool getwindowname $PID)
    if [[ $TITLE == *"journalctl"* ]]; then
        EXISTS=1
        break
    fi
done

if [ $EXISTS == 0 ]; then
    `alacritty -t "journalctl" -e "journalctl-ccze"` &
fi

telegram-desktop &
sleep 2

EXISTS=0

for PID in $PIDS; do
    TITLE=$(xdotool getwindowname $PID)
    if [[ $TITLE == *"ytop"* ]]; then
        EXISTS=1
        break
    fi
done

if [ $EXISTS == 0 ]; then
    `alacritty -t "ytop" -e ytop` &
fi
