#!/bin/bash

cache="$HOME/.cache/yay"

array=($( ls -1p $cache | grep / | sed 's/^\(.*\)/"\1"/') )
list=$(pacman -Qqm)

for i in "${array[@]}"
do
    package=$(echo $i | tr -d '"' | sed 's/.$//')
    if ! grep -q "$package" <<< "$list"; then
        newline="\n"
        rm -rf $cache/$package
        printf "::\033[1;37m %s\033[0m is not installed -- removing cache\n" "$package"
    fi
done
printf "$newline"

yay -Syu --devel --overwrite '*' --sudoloop  --noanswerdiff --noansweredit --noconfirm

cd $cache
for directory in */; do
    cd $directory
    cleanup=$(ls --group-directories-first -t | grep ".pkg.tar.\(xz\|zst\)$" | tail -n +3 | xargs)
    if [ "$cleanup" != "" ]; then
        rm $cleanup
    fi
    cd ..
done
